---
title: "Resume"
---

## Paper Resume

<iframe src="files/summer2025_resume.pdf" width="100%" height="600px" style="border: none;">

This browser does not support PDFs. Please download the PDF to view it: <a href="files/resume.pdf">Download PDF</a>.

</iframe>

## Skills

R, R Shiny, Python, SQL, Excel, Adobe Customer Journey Analytics, Adobe Experience Platform Tableau, JavaScript, Qlik Sense, Quarto, AMPL, Markdown 

## Related Work Experience

### WillowTree (Now TELUS Digital)

*Analytics Intern* \| *Summer 2025*

-   Designed, implemented, and tested a unified, scalable schema for a client’s web and mobile applications using Adobe tools. 
-   Identified over 1.2 million misclassified web analytics events and over 15,000 rows of inaccurate revenue data in a client database using BigQuery. 
-   Developed a bot classification model with Python to improve a client’s bot recognition, reducing skew in web analytics data. 

### QlikTech Inc.

*Analytics Intern* \| *March 2022 -- March 2024 (Seasonal)*

-   Contributed to the creation and editing of technical documentation for annual software product conference for 3000 users

-   Co-created customer relationship data analysis application using QlikTech software which used KPIs and other data to monitor keymetrics such as website traffic

-   Used Excel to organize thousands of employee equity documents to ensure the accuracy and completeness of each employee's files

-   Shadowed a Senior Data Scientist to learn key industry techniques

## Research

### [UNC Sports Analytics Intelligence Lab](https://supermariogiacomazzo.github.io/sports-analytics-intelligence-laboratory/)

*Undergraduate Student Analyst* \| *September 2024-Present*

-   Diagnose and investigate ways to improve athlete training and team performance across UNC Division 1 athletics
-   Clearly and simply articulate technical sports analytics research to coaches without analytical expertise
-   Construct informative and interactive visualizations and mathematical models, and analyze complex datasets using software such as R
-   Collaborate with other undergraduate and graduate students on case competitions and independent research projects
-   Utilize crucial data science skills such as web-scraping, data wrangling, and visualization

## Additional Work Experience

### Lake Owego Camp for Boys

*Junior Division Unit Leader/Bunk Counselor* \| *June 2022-August 2024 (Seasonal)*

-   Coordinated creative, fun, daily activities for 100 campers aged 7-12

-   Managed disputes between campers and assisted counselors with day-to-day issues

-   Chosen to share responsibility for youngest first-time campers during multiple summers

-   Promoted to Unit Leader for the youngest division of campers after second summer

### Primo's Hoagies

*Sandwich Dresser/Cashier* \| *August 2020 - June 2021*

-   Hand-crafted dozens of sandwiches per hour in a fast-paced environment, focusing on quality and presentation to ensure repeat customers

-   Promoted to front-of-store customer service duties and given store-closing responsibility

## High School Positions

### Upper Dublin High School Baseball Team

*Statistics Manager* \| *Spring 2022*

-   Collected and organized 25 players' statistics at each game

-   Updated live play-by-play game data and used it to advise coaches on in-game decisions, such as pinch-hitting and relief pitcher decisions

-   Selected by coaching staff from a pool of 50 students to perform the role

### Upper Dublin High School Basketball Team

*Analytics Innovator* \| *November 2021-February 2022*

-   Spent 15 hours self-learning QlikTech analytics software

-   Created a custom app using QlikTech software highlighting performance, including individual shot-making and team offensive efficiency

-   Empowered coaches with an innovative decision-making process to determine the distribution of minutes for each player and allowed for the creation of a new offensive scheme

## Certifications

### Adobe Customer Journey Analytics Business Practitioner

*Passed June 2025*
